# Check on http://lint.travis-ci.org/ after modifying! Taken and modified
# from https://github.com/biocore/scikit-bio/blob/master/.travis.yml
language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  - conda create --yes -n env_name python=$TRAVIS_PYTHON_VERSION pip numpy scipy matplotlib pandas ipython-notebook pyqt scikit-learn
  - source activate env_name
  - pip install scikit-bio runipy six requests ete2 qiime_default_reference

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - python runipynbs.py
